[program:talksasa-container-terminal-ws]
process_name=%(program_name)s
command=php /var/www/talksasa-cloud/artisan container:terminal-ws
directory=/var/www/talksasa-cloud
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/talksasa/container-terminal-ws.log
stopwaitsecs=10
